Use zsh
 * Create zsh folder
 * Add install zsh script
 * Add symlink function

diff --git a/framework b/framework
--- a/framework
+++ b/framework
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+
+DOTF=`dirname ${BASH_SOURCE[0]-$0}`
+export DOTF=`cd $DOTF && pwd`
+
+source $DOTF/zsh/core.zsh
+
 # Colors {{{1
 export BLACK="\033[30m"
 export GRAY="\033[1;30m"
@@ -120,4 +126,49 @@ brew_cask_install() {
 
 has_brew_cask_package() {
   [ "`brew cask list | grep \"^$1\$\"`" != "" ]
+}
+
+# backup {{{1
+backup() {
+  info "\n  backing up to ${1}.backup"
+  mv -f "$1" "${1}.backup"
+  if [ $? == 0 ]; then return; fi
+
+  info "  trying with sudo:"
+  sudo mv -f "$1" "${1}.backup"
+  if [ $? != 0 ]; then
+    error "FAILED"
+    exit 1
+  fi
+}
+
+# symlink {{{1
+symlink() {
+  source=$1
+  target=$2
+
+  bullet "Linking $source\n      ==> ${target}... "
+  if [ -e "$target" ]; then
+    if [ -h "$target" ]; then
+      if [ "$source" == "$(readlink "$target")" ]; then
+        info " already exists"
+        return
+      fi
+    fi
+
+    backup "$target"
+  fi
+
+  ln -sf "$source" "$target"
+  if [ $? != 0 ]; then
+    info "  Can't create link, trying with sudo:"
+    sudo ln -sf "$source" "$target"
+    if [ $? != 0 ]; then
+      error "failed"
+      exit 1
+    fi
+  fi
+  if [ $? == 0 ]; then
+    success "done"
+  fi
 }
